### ISSUE TITLE
Request for midi to bcseq conversion, and questions

### ISSUE THREAD

**Issue by Kewlan** [Gota7/SequenceConvert#1]
Hi, I'm from the OoT3D community and I'm looking into adding custom music shuffling. My plan is to have the rando app replace `bcseq`s in the `QueenSound.bcsar` file by porting your code from Citric Composer. So first of all I will ask if you're okay with that?

The current roadblock is to create new `bcseq` files. At worst I know it's possible to manually write the cseq files and then convert to `bcseq` with the executable from this repo, but being able to convert from OoT64's custom song library from `midi` directly to `bcseq` would of course make it much faster!
Is this something you think you could implement? How much effort would it take?

I've also asked for help with this at the seq64 repo: https://github.com/sauraen/seq64/issues/27

**Comment by Gota7** [comment]
Oh yeah, I'm definitely fine with that port what you like. Though I no longer maintain my old sound tools. Unfortunately, if you want MIDI support you'll have to do it yourself. I starting making an MIDI to SSEQ converter for DS (in Nitro Studio 2) that should mostly apply here though it is not quite finished.
